name: rent_manager
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rename: ^2.0.1
  # flutter pub global activate rename
  # flutter pub global run rename --appname "Rent Manager"

  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7

  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  firebase_auth: ^2.0.0

  get: ^4.6.5
  get_storage: ^2.0.3
  sizer: ^2.0.13
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  url_launcher: ^6.0.0
  dotted_border: ^2.0.0
  animate_do: ^2.1.0
  file_picker: ^5.0.1
  permission_handler: ^10.0.0
  easy_localization: ^3.0.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_lints: ^2.0.0
  #flutter packages pub run build_runner build

flutter:

  uses-material-design: true

  assets:
    - assets/translations/




# flutter pub get
# flutter pub run flutter_launcher_icons:main -f pubspec.yaml
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: #FFFFFFFF

flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: "#E3EBEC"
  image: assets/icon/logo.png
  color_dark: "#212230"
  image_dark: assets/icon/logo.png
  android_gravity: center
  fullscreen: true

